[package]
name = "demoman"
version = "0.1.0"
description = "The TF2 Demo Manager"
authors = ["Narcha"]
license = "GPL-3.0-only"
repository = "https://github.com/Narcha/DemoMan-tauri"
default-run = "demoman"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["api-all"] }
simple_logger = "2.2.0"
log = "0.4.17"

[dependencies.tauri-plugin-store]
# To be replaced by a proper package when it becomes available
git = "https://github.com/tauri-apps/tauri-plugin-store"
branch = "dev"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
