name: Check PR

on:
  pull_request:
    branches-ignore: ["v1"]
  workflow_dispatch:

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: install frontend dependencies
        run: npm clean-install

      - uses: tauri-apps/tauri-action@v0
        with:
          # Only build in debug mode so the following
          # steps don't have to compile again.
          includeDebug: true
          includeRelease: false
          args: "--no-bundle -- --locked"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run backend tests
        run: cargo test --all-features

      - name: Lint backend
        run: |
          cargo fmt --check
          cargo clippy --all-features --tests -- -D warnings

      - name: Lint frontend
        run: |
          npm run typecheck
          npx biome ci
